language: ruby
rvm:
  - 1.9.3
  - 2.0.0
services:
  - mysql
before_script:
  - "cp config/settings.yml.example config/settings.yml"
  - "cp config/database.yml.example config/database.yml"
  - "sed -i 's/username: aclog/username: /g' config/database.yml"
  - "cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb"
  - "sed -i s/replace_here/$(rake secret)/g config/initializers/secret_token.rb"
script:
  - "RAILS_ENV=test bundle exec rake db:drop db:create db:migrate"
  - "RAILS_ENV=test bundle exec rake tmp:create"
  - "RAILS_ENV=test bundle exec rails runner script/start.rb start"
  - "RAILS_ENV=test bundle exec rake spec"

