language: ruby
rvm:
  - 2.0.0
  - 1.9.3
services:
  - mysql
before_script:
  - "cp config/settings.yml.example config/settings.yml"
  - "cp config/database.yml.example config/database.yml"
  - "sed -i 's/username: aclog/username: /g' config/database.yml"
  - "cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb"
  - "sed -i s/replace_here/$(rake secret)/g config/initializers/secret_token.rb"
  - "mysql -e 'CREATE DATABASE aclog_test;'"
script:
  - "RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec"

