#consumer:
#    - key: <%= ENV["CONSUMER_KEY"] %>
#    secret: <%= ENV["CONSUMER_SECRET"] %>
consumer_version: 1
worker_count: <%= ENV["ACLOG_WORKER_COUNT"] %>
secret_key: <%= ENV["ACLOG_SECRET_KEY"] %>
db_proxy_port: <%= ENV["ACLOG_DB_PROXY_PORT"] %>
register_server_path: <%= ENV["ACLOG_REGISTER_SERVER_PATH"] %>
tweet_url: <%= ENV["ACLOG_TWEET_URL"] %>
#notification:
#  consumer:
#    key: <%= ENV["ACLOG_NOTIFICATION_CONSUMER_KEY"] %>
#    secret: <%= ENV["ACLOG_NOTIFICATION_CONSUMER_SECRET"] %>
#  token:
#    token: <%= ENV["ACLOG_NOTIFICATION_OAUTH_TOKEN"] %>
#    secret: <%= ENV["ACLOG_NOTIFICATION_OAUTH_TOKEN_SECRET"] %>
